### ISSUE TITLE
using <l-polyline-measure> is not work

### ISSUE THREAD

**Issue by Morxi** [mikeu/vue2-leaflet-polyline-measure#1]
I tried follow readme.md to install package and coding, then ,I get a error from browser console

> [Vue warn]: Unknown custom element: \<l-polyline-measure\> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by mikeu** [comment]
There was a typo in the readme example code. To add the control to the map, it has to use the same name as registered elsewhere, so it should be:
```html
<l-map>
  <l-control-polyline-measure :options="{ showUnitControl: true }" position="bottomright"/>
  <!-- other map components -->
</l-map>
```

The small difference is adding "control" so that it uses `<l-control-polyline-measure...` instead of `<l-polyline-measure...` in the template.

I'll update the readme to fix that issue, thank you for reporting it!
