### ISSUE TITLE
npm installation failed

### ISSUE THREAD

**Issue by AmberXie** [mikeu/vue2-leaflet-polyline-measure#2]
When I tried to use the command to install this component : 
npm install --save vue2-leaflet-polyline-measure
I got the error: 
`npm ERR! path git`
`npm ERR! code ENOENT`
`npm ERR! errno ENOENT`
`npm ERR! syscall spawn git`
`npm ERR! enoent Error while executing:`
`npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/ppete2/Leaflet.PolylineMeasure.git`
`npm ERR! enoent`
`npm ERR! enoent`
`npm ERR! enoent spawn git ENOENT`
`npm ERR! enoent This is related to npm not being able to find a file.`
`npm ERR! enoent`

But when I tried to install other plugins, such as "vue2-leaflet-geosearch", everything works well.

**Comment by mikeu** [comment]
@AmberXie do you have git installed on your system and available in your path? [This stackoverflow question](https://stackoverflow.com/questions/56473680/npm-install-shows-error-with-git-not-found) seems to be the same issue you are seeing, and the accepted answer is to install git.

Unfortunately the underlying Leaflet plugin that this component wraps for Vue2Leaflet does not have an official npm package, and so is installed via `git clone`. I haven't been able to reproduce the issue on my end, the component installs correctly, but I also have git installed so that is likely why.

**Comment by AmberXie** [comment]
Thanks a lot for your reply!
After the installation of Git, the problem is solved.
